import test from 'node:test';
import assert from 'node:assert/strict';
import '../route-editor.js';
const base=()=>({authoritative:false,coordinateWidth:1000,coordinateHeight:800,paths:[{type:'railway',points:[[100,100],[200,100],[300,100]]},{type:'airport',points:[[500,500],[600,500]],color:'#ff4949'}]});
function setup(storage){const nodes=new Map();const el=id=>{if(!nodes.has(id))nodes.set(id,{value:'railway',setAttribute(){}});return nodes.get(id);};const doc={getElementById:el};const map=storage||new Map();const store=storage?.getItem?storage:{getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v)};const editor=new globalThis.RFRouteEditor({width:1000,height:800,document:doc,storage:store,onChange(){},isVisible:()=>true,getCities:()=>[{city_id:7,x_position:150,y_position:150}]});editor.load(base());editor.open();return {editor,el,store};}
const view={scale:1,offsetX:0,offsetY:0};const e=(x,y,id=1)=>({clientX:x,clientY:y,pointerId:id});
test('重做恢復刪除與拖曳，按鈕隨紀錄啟閉；新修改清除重做',()=>{const {editor,el}=setup();assert.equal(el('editorRedo').disabled,true);editor.selected=0;el('editorDelete').onclick();assert.equal(editor.paths.length,1);editor.undo();assert.equal(editor.paths.length,2);assert.equal(el('editorRedo').disabled,false);el('editorRedo').onclick();assert.equal(editor.paths.length,1);assert.equal(el('editorRedo').disabled,true);editor.undo();editor.selected=0;editor.down(e(200,100),view);editor.move(e(240,180),view);editor.up(e(240,180));assert.equal(el('editorRedo').disabled,true);const modified=JSON.stringify(editor.data);editor.undo();editor.redo();assert.equal(JSON.stringify(editor.data),modified);});
test('新增節點及完成新增可逐步復原／重做，保留種類與端點',()=>{const {editor,el}=setup();editor.mode='add';el('editorType').value='dirt';for(const p of [[150,150],[400,400]]){editor.down(e(...p),view);editor.up(e(...p));}editor.undo();assert.equal(editor.pending.length,1);editor.redo();assert.equal(editor.pending.length,2);editor.finish();const finished=JSON.stringify(editor.data);editor.undo();assert.equal(editor.pending.length,2);assert.equal(editor.mode,'add');assert.equal(editor.paths.length,2);editor.redo();assert.equal(editor.mode,'select');assert.equal(editor.pending.length,0);assert.equal(JSON.stringify(editor.data),finished);});
test('只是點選控制點不清除重做；取消拖曳保留重做紀錄',()=>{const {editor}=setup();editor.selected=0;editor.down(e(200,100),view);editor.move(e(240,180),view);editor.up(e(240,180));editor.undo();editor.down(e(100,100),view);editor.up(e(100,100));assert.equal(editor.future.length,1);editor.down(e(100,100),view);editor.move(e(110,120),view);editor.up(e(110,120),true);assert.equal(editor.future.length,1);editor.redo();assert.deepEqual(editor.paths[0].points[1],[240,180]);});
test('選線、拖曳折點、端點吸附、復原與重新載入草稿',()=>{const {editor,store}=setup();assert.equal(editor.down(e(220,100),view),true);editor.up(e(220,100));assert.equal(editor.selected,0);editor.down(e(100,100),view);editor.move(e(149,150),view);editor.up(e(149,150));assert.deepEqual(editor.paths[0].points[0],[150,150]);assert.equal(editor.paths[0].from,7);assert.deepEqual(setup(store).editor.paths,editor.paths);editor.undo();assert.deepEqual(editor.data,base());});
test('新增、刪除、復原，不改機場層；取消拖曳不保存',()=>{const {editor,el}=setup();editor.mode='add';el('editorType').value='dirt';editor.down(e(150,150),view);editor.up(e(150,150));editor.down(e(400,400),view);editor.up(e(400,400));editor.finish();assert.equal(editor.paths.length,3);assert.equal(editor.paths[2].from,7);assert.equal(editor.paths[2].type,'dirt');el('editorDelete').onclick();assert.equal(editor.paths.length,2);editor.undo();assert.equal(editor.paths.length,3);assert.deepEqual(editor.paths[1],base().paths[1]);editor.selected=0;editor.down(e(200,100),view);editor.move(e(230,150),view);editor.up(e(230,150),true);assert.deepEqual(editor.paths[0],base().paths[0]);});
test('曲線採樣、控制點修改，存檔與繪圖採用相同曲線',()=>{const {editor}=setup();editor.selected=0;const confirm=globalThis.confirm;globalThis.confirm=()=>true;try{editor.smooth();}finally{globalThis.confirm=confirm;}const r=editor.paths[0];assert.equal(r.curves.length,1);editor.down(e(r.curves[0][0],100),view);editor.move(e(175,160),view);editor.up(e(175,160));assert.equal(r.curves[0][1],160);assert.deepEqual(r.points,globalThis.RFSampleRouteCurve(r));assert.deepEqual(r.points.at(-1),[300,100]);editor.undo();assert.equal(editor.paths[0].curves[0][1],100);});
test('拒絕錯誤匯入、座標尺寸與非有限控制點；保存失敗提示匯出',()=>{assert.throws(()=>globalThis.RFValidateRouteGeometry({...base(),coordinateWidth:1},1000,800));const bad=base();bad.paths[0].curves=[[1,2,3,4,Infinity,6]];assert.throws(()=>globalThis.RFValidateRouteGeometry(bad,1000,800));const {editor}=setup({getItem(){return null;},setItem(){throw Error('quota');}});editor.save();assert.match(editor.message,/匯出/);});
test('底圖版本變更不靜默套用舊草稿；移動模式不攔截地圖操作',()=>{const {store}=setup();const old=base();old.paths.pop();store.setItem('rf-map-route-editor-v1',JSON.stringify({base:JSON.stringify(old),data:old}));const {editor}=setup(store);assert.deepEqual(editor.data,base());assert.match(editor.message,/未自動套用/);editor.mode='pan';assert.equal(editor.down(e(200,100),view),false);});
